### ISSUE TITLE
Create paragraph type feature for longer questions and answers

### ISSUE THREAD

**Issue by Amuodmi** [Dj-Viking/Nomad-Lang#69]
Long formed questions and answers in the field currently display as a run-on sentence.  Could be helpful to have them display as a paragraph style instead. 

![check box alignment](https://user-images.githubusercontent.com/104099393/176965936-814238ef-c5af-4092-aa92-a7cfc7105590.png)

![check box 2](https://user-images.githubusercontent.com/104099393/176965940-3506b007-7d7a-4148-853e-b75f4dfe92aa.png)

**Comment by Dj-Viking** [comment]
Oops I think i missed the scenario where the front side text is longer and should be wrapped I'll re-open this

**Comment by Amuodmi** [comment]
![Screen Shot 2022-07-17 at 15 23 04](https://user-images.githubusercontent.com/104099393/179423208-950f3b32-89a2-4bf3-b2f2-4f61e304a7f2.png)

The toolkit could use the same adjustment, just in case.

**Comment by Amuodmi** [comment]
![Screen Shot 2022-07-17 at 15 18 32](https://user-images.githubusercontent.com/104099393/179423258-9cb534db-461e-4e0e-97a3-e5683d077379.png)

Oh, and also this is happening on my side. I am not sure why. It is only for this specific card.

**Comment by Dj-Viking** [comment]
if you're curious why thats happening for the tooltip the function here is determining whether or not to render a tooltip on the button because it's such a long length of an answer

* [link to function parsing the answer text](https://github.com/Dj-Viking/Nomad-Lang/blob/957da9a0ceed8fb4dae9ed280967714aa3f44847/client/src/components/ChoiceButton.vue#L75)

**Comment by Dj-Viking** [comment]
@Amuodmi Thank you so much again for bringing these issues up, this helps make the app much better as we iterate on ideas. This is always open for modification and improvement. this app is kind of a spagetti mess but that's how it goes in the beginning stages before refactoring.
